# This is a basic workflow to help you get started with Actions

name: UpdateContributors

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip

    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - run: pip install PyGithub

    - run: |
        import json
        import os
        from github import Github
        g = Github(os.getenv("GITHUB_TOKEN"))
        repo = g.get_repo(os.getenv("GITHUB_REPOSITORY"))
        contributors = []
        for contributor in repo.get_contributors():
          name = contributor.name or contributor.login
          contributors += [{ 'name': name, 'url': contributor.html_url }]
        with open('_data/contributori.json', 'w') as outfile:
          json.dump(contributors, outfile)
      shell: python

    - run: |
        git config --local user.name "GitHub Action"
        git add _data/contributori.json
        git commit -m "Aggiorno _data/contributori.json" && git push || :
